# Copyright (c) 2025-2026 Cherified Systems LLC
#
# SPDX-License-Identifier: MIT

.PHONY: coq clean force

coq: Makefile.coq.all $(VS) ./PrettyPrinter/FixLits
	$(MAKE) -f Makefile.coq.all

./PrettyPrinter/FixLits: ./PrettyPrinter/FixLits.hs
	ghc --make -package text ./PrettyPrinter/FixLits.hs -o ./PrettyPrinter/FixLits

define Main_rule
$(1)Compile.hs: coq

HASKELLS := $(wildcard PrettyPrinter/*)

$(1)Rtl: $(HASKELLS) $(1)Compile.hs
	grep -q "import qualified Data" $(1)Compile.hs || ./PrettyPrinter/FixLits $(1)Compile.hs
	grep -q "import qualified Data" $(1)Compile.hs || sed -i "/import qualified Prelude/aimport qualified Data.Bits\nimport qualified Data.Char" $(1)Compile.hs
	ghc --make -j -i./PrettyPrinter -i$(1) -main-is Rtl ./PrettyPrinter/Rtl.hs -odir $(1) -hidir $(1) -o $(1)Rtl

$(1)Rtl.sv: $(1)Rtl
	$(1)Rtl > $(1)Rtl.sv

$(1)obj_dir/Vtb: $(1)Rtl.sv
	verilator -Wno-CMPCONST --top tb --binary -I./Verilog --Mdir $(1)obj_dir $(1)Rtl.sv

$(1)SimRtl.sv: $(1)Rtl
	$(1)Rtl s > $(1)SimRtl.sv

$(1)sim_obj_dir/Vtb: $(1)SimRtl.sv
	verilator -Wno-CMPCONST --top tb --binary -I./Verilog --Mdir $(1)sim_obj_dir $(1)SimRtl.sv
endef

force:

Makefile.coq.all: force
	$(COQBIN)rocq makefile --no-rocq-package-warning -f _CoqProject -o Makefile.coq.all

clean:: Makefile.coq.all
	$(MAKE) -f Makefile.coq.all clean
	find . -type f -name '*.v.d' -exec rm {} \;
	find . -type f -name '*.glob' -exec rm {} \;
	find . -type f -name '*.vo' -exec rm {} \;
	find . -type f -name '*.vos' -exec rm {} \;
	find . -type f -name '*.vok' -exec rm {} \;
	find . -type f -name '*.~' -exec rm {} \;
	find . -type f -name '*.hi' -exec rm {} \;
	find . -type f -name '*.o' -exec rm {} \;
	find . -type f -name '*.aux' -exec rm {} \;
	find . -type f -name '*.ho' -exec rm {} \;
	find . -type f -name 'Compile.hs' -exec rm {} \;
	find . -type f -name 'Rtl' -exec rm {} \;
	find . -type f -name 'Rtl.sv' -exec rm {} \;
	find . -type f -name 'SimRtl.sv' -exec rm {} \;
	find . -type d -depth -name 'obj_dir' -exec rm -rf {} \;
	find . -type d -depth -name 'sim_obj_dir' -exec rm -rf {} \;
	rm -f PrettyPrinter/FixLits
	rm -f Makefile.coq.all Makefile.coq.all.conf .Makefile.coq.all.d
	rm -f .nia.cache .lia.cache

